openapi: 3.0.1
info:
  title: type_changed
  version: "1.0"
paths:
  /api/Parameters:
    get:
      operationId: Parameters_Get
      responses: {}
      x-ms-long-running-operation: true
    put:
      operationId: Parameters_Put
      parameters:
        - name: database
          required: true
      responses: {}
      x-ms-long-running-operation: false
