openapi: 3.0.1
info:
  title: removed_definition
  version: "1.0"
servers:
  - url: http://localhost:8000
paths:
  /api/Parameters:
    put:
      parameters:
        - $ref: '#/components/parameters/skipParam'
        - $ref: '#/components/parameters/skipParam'
        - $ref: '#/components/parameters/limitParam'
components:
  parameters:
    skipParam:
      name: skip
      in: query
      description: number of items to skip
      schema:
        type: integer
        format: int32
    limitParam:
      name: limitParam
      in: query
      description: max records to return
      schema:
        type: integer
        format: int32
