openapi: 3.0.1
info:
  title: Added Schema in response
  version: "2.0"
servers:
  - url: http://localhost:8000
paths:
  /api/Parameters:
    put:
      tags:
        - Parameters
      operationId: Parameters_Put
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
components:
  schemas:
    Pet:
      type: object
      discriminator:
        propertyName: petType
      properties:
        name:
          type: string
        petType:
          type: string
          enum:
            - cat
            - dot
      required:
        - name
        - petType
