openapi: 3.0.1
info:
  title: removed_operation
  version: "1.0"
paths:
  /api/Paths:
    get:
      operationId: Paths_Get
      responses: {}
  /api/Operations:
    get:
      operationId: Operations_Get
      responses: {}
    post:
      operationId: Operations_Post
      responses: {}
