openapi: 3.0.0
info:
  title: Petstore API
  version: "2.0"
paths:
  /pets:
    post:
      description: Post multiple pets
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schema/Pet'
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: integer
components:
  schemas:
    Pet:
      type: object
      properties:
        name:
          type: string
        petType:
          type: string
          enum:
            - cat
            - dog
  requestBodies:
    PetBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schema/Pet'
