openapi: 3.0.0
info:
  version: 2.0.0
  title: Swagger PetStore
  description: A sample API that uses a petStore as an example to demonstrate features in the OpenAPI 3.0 specification
servers:
  - url: http://petstore.swagger.io/api
paths:
  /pets:
    get:
      description: Returns all pets from the system.
      operationId: findPets
      responses:
        "200":
          description: pet response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        "404":
          description: not found response
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  error:
                    type: string
                  message:
                    type: string
components:
  schemas:
    Pet:
      type: object
      required:
        - petType
      properties:
        name:
          type: string
        petType:
          type: string
