openapi: 3.0.0
info:
  title: My API
  version: 0.2.0
paths:
  /order/{path}:
    post:
      parameters:
        - name: path
          in: path
          required: true
          schema:
            type: string
            enum:
              - abc
              - def
        - name: query
          in: query
          schema:
            type: string
            enum:
              - ghi
              - jkl
      requestBody:
        content:
          application/json:
            schema:
              properties:
                foo:
                  type: string
                  enum:
                    - mno
                    - pqr
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                properties:
                  bar:
                    type: string
                    enum:
                      - stu
                      - zzzzzz
                      - vwx
