openapi: 3.0.0
info:
  title: Petstore API
  version: "2.0"
paths:
  /pets:
    get:
      description: Get all pets from Petstore
      parameters:
        - name: pageParam
          in: query
          style: pipeDelimited
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
  /pets/{id}:
    parameters:
      - name: PetId
        in: path
        required: true
        style: matrix
    post:
      description: Register a new pet
      parameters:
        - $ref: '#/components/parameters/PetParameter'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Pet:
      type: object
      properties:
        name:
          type: string
        petType:
          type: string
  parameters:
    PetParameter:
      name: PetParameter
      in: query
      style: deepObject
      schema:
        $ref: '#/components/schemas/Pet'
