openapi: 3.0.1
info:
  title: added_path
  version: "2.0"
paths:
  /api/Paths:
    get:
      operationId: Paths_Get
      responses: {}
  /api/Operations:
    get:
      operationId: Operations_Get
      responses: {}
