openapi: 3.0.0
info:
  title: removed_definition
  version: "2.0"
servers:
  - url: http://localhost:8000
  - url: https://localhost:8000
paths:
  /pets:
    get:
      parameters:
        - $ref: '#/components/parameters/limitParam'
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  maxRequest:
                    type: integer
                    multipleOf: 200
components:
  schemas:
    limitParam:
      type: object
      properties:
        accessKey:
          type: string
          pattern: ^\d{3}-\d{2}-\d{4}$
        redirectUrl:
          type: array
          items:
            type: string
        constrainsItems:
          type: string
          enum:
            - item1
            - item2
            - item4
  parameters:
    limitParam:
      name: limit
      in: query
      required: true
      schema:
        $ref: '#/components/schemas/limitParam'
