openapi: 3.0.0
info:
  title: Petstore API
  version: "2.0"
paths:
  /pets:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Pet'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Pet'
  /pets/{id}:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: integer
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
            application/xml:
              schema:
                $ref: '#/components/schemas/Pet'
        "404":
          $ref: '#/components/responses/ErrorResponse'
components:
  schemas:
    Pet:
      type: object
      properties:
        name:
          type: string
        petType:
          type: string
          enum:
            - cat
            - dog
    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
  responses:
    ErrorResponse:
      content:
        text/plain:
          schema:
            type: string
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
