openapi: 3.0.0
info:
  title: My API
  version: 0.2.0
paths:
  /orders:
    get:
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Commande"
components:
  schemas:
    Commande:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
