x-generator: NSwag v14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0))
openapi: 3.0.0
info:
  title: My Title
  version: "1.0"
paths:
  /api/public/form:
    post:
      operationId: PostTicket
      requestBody:
        x-name: request
        content:
          application/json:
            schema:
              nullable: true
              oneOf:
                - $ref: '#/components/schemas/TicketPostRequest'
        required: true
        x-position: 1
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketResponse'
  /api/v1/public/productContent:
    get:
      operationId: PublicDevice_GetProductContent
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentModel'
components:
  schemas:
    ContentModel:
      type: object
      additionalProperties: false
      required:
        - testHiddenNotNullableProperty
      properties:
        name:
          type: string
          nullable: true
        testHiddenNotNullableProperty:
          type: string
    TicketResponse:
      type: object
      properties:
        ticket:
          nullable: true
          oneOf:
            - $ref: '#/components/schemas/TicketObject'
    TicketObject:
      type: object
      properties:
        allow_attachments:
          type: boolean
    TicketPostRequest:
      type: object
      additionalProperties: false
      required:
        - email
      properties:
        email:
          type: string
          minLength: 1
