openapi: 3.0.1
info:
  title: operation_check_01
  version: "2.0"
paths:
  /api/Path:
    get:
      operationId: Paths_Get
      responses: {}
  /api/Operations:
    get:
      operationId: Operations_Get
      responses: {}
    post:
      operationId: Operations_Post
      responses:
        "200":
          description: null
  /api/Parameters/{a}:
    get:
      operationId: Parameters_Get
      responses: {}
  /api/Responses:
    get:
      operationId: Responses_Get
      responses:
        "200":
          description: null
        "202":
          description: null
        "400":
          description: null
