name: Continuous Integration

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test --no-build
      - name: Run CLI with absolute paths
        run: >
          dotnet run
          --no-build
          --project src/Criteo.OpenApi.Comparator.Cli/Criteo.OpenApi.Comparator.Cli.csproj
          --framework net8
          -o $PWD/src/Criteo.OpenApi.Comparator.UTest/Resource/reference_redirection_type_changed/old.yaml
          -n $PWD/src/Criteo.OpenApi.Comparator.UTest/Resource/reference_redirection_type_changed/new.yaml
        if: always()
      - name: Run CLI with relative paths
        run: >
          dotnet run
          --no-build
          --project src/Criteo.OpenApi.Comparator.Cli/Criteo.OpenApi.Comparator.Cli.csproj
          --framework net8
          -o src/Criteo.OpenApi.Comparator.UTest/Resource/reference_redirection_type_changed/old.yaml
          -n src/Criteo.OpenApi.Comparator.UTest/Resource/reference_redirection_type_changed/new.yaml
        if: always()
      - name: Run CLI with URLs
        run: >
          dotnet run
          --no-build
          --project src/Criteo.OpenApi.Comparator.Cli/Criteo.OpenApi.Comparator.Cli.csproj
          --framework net8
          -o https://raw.githubusercontent.com/criteo/openapi-comparator/main/src/Criteo.OpenApi.Comparator.UTest/Resource/reference_redirection_type_changed/old.yaml
          -n https://raw.githubusercontent.com/criteo/openapi-comparator/main/src/Criteo.OpenApi.Comparator.UTest/Resource/reference_redirection_type_changed/new.yaml
        if: always()
